- name: copy prometheus configuration
  ansible.builtin.template:
    src: prometheus.yml
    dest: /opt/prometheus/prometheus.yml

- name: restart prmmetheus service
  ansible.builtin.systemd:
    name: prometheus
    state: restarted

- name: wait to restart prometheus service
  ansible.builtin.wait_for:
    host: 0.0.0.0
    port: 9090
    delay: 10
    timeout: 30