

- name: Add Roboshop Application User
  ansible.builtin.user:
    name: roboshop
  register: appuser


- name: cleanup old app content
  ansible.builtin.file:
    path: /home/roboshop/{{COMPONENT}}
    state: absent

- name: Create Application Directory
  ansible.builtin.file:
    path: /home/roboshop/{{COMPONENT}}-tmp
    state: directory
    owner: roboshop
    group: roboshop


#- name: Downloading application content
#  ansible.builtin.unarchive:
#    src: https://github.com/roboshop-devops-project/{{COMPONENT}}/archive/main.zip
#    dest: /tmp
#    remote_src: yes

- name: Downloading Application Content
  ansible.builtin.unarchive:
    src: http://{{NEXUS_USER}}:{{NEXUS_PASS}}@nexus.roboshop.internal:8081/repository/{{COMPONENT}}/{{COMPONENT}}-{{APP_VERSION}}.zip
    dest: /home/roboshop/{{COMPONENT}}-tmp
    remote_src: yes
  become_user: roboshop

#- name: copy Extracted content
#  ansible.builtin.copy:
#    src: /tmp/{{COMPONENT}}-main/
#    dest: /home/roboshop/{{COMPONENT}}/
#    remote_src: yes
#  become_user: roboshop