
- name: install java
  ansible.builtin.yum:
    name: java
    state: installed

- name: import app-prereq task file
  ansible.builtin.import_tasks: app-prereq.yml

- name: install maven dependencies
  ansible.builtin.shell: mvn clean package && mv target/${COMPONENT}-1.0.jar ${COMPONENT}.jar
  args:
    chdir: /home/roboshop/{{COMPONENT}}
  become_user: roboshop


- name: Import SystemD tasks
  ansible.builtin.import_tasks: systemd.yml