groups:
  - name: Alerts
    rules:
      - alert: InstanceDown
        expr: up == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          {% raw %}summary: "Instance Down - [{{ $labels.instance }}]"{% endraw %}

          {% raw %}description: "Instance Down - [{{ $labels.instance }}]"{% endraw %}

      - alert: MemoryHighUsage
        expr: node_memory_used_percent > 80
        labels:
          severity: critical
        annotations:
          {% raw %}summary: "High Memory Usage - [{{ $labels.Name }}]"{% endraw %}

          {% raw %}description: "High Memory Usage - [{{ $labels.Name }}]\n Private IP Address = [{{ $labels.Name }}]"{% endraw %}


      - alert: CPUHighUsage
        expr: avg by (instance) (100 - (rate(node_cpu_seconds_total{mode="idle"}[1m]) * 100)) > 80
        labels:
          severity: critical
        annotations:
          {% raw %}summary: "High CPU Usage - [{{ $labels.Name }}]"{% endraw %}

          {% raw %}description: "High CPU Usage - [{{ $labels.Name }}]\n Private IP Address = [{{ $labels.Name }}]"{% endraw %}



